### ISSUE TITLE
Not ERIS 1.0.0 compliant

### ISSUE THREAD

**Issue by ghost** [mguentner/eris-rs#1]
https://eris.codeberg.page/spec/#name-changelog

**Comment by mguentner** [comment]
Thanks for the heads up. It compliant now except for the chacha 256 GiB test, I suspect that this might be out of spec actually for chacha20:
https://github.com/RustCrypto/stream-ciphers/issues/240

**Comment by ghost** [comment]
I've had problems with other Chacha20 libraries and the long tests, so its not just you.

**Comment by ghost** [comment]
Thanks for the update, eris-rs is back on the list of compliant implementations https://eris.codeberg.page/
